// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfnxYL5Es6q_Jldkp6JvNajCgzUu6Dwf0',
    appId: '1:220189526733:web:e372b48561d3519474b784',
    messagingSenderId: '220189526733',
    projectId: 'flutterapp1-c8e90',
    authDomain: 'flutterapp1-c8e90.firebaseapp.com',
    storageBucket: 'flutterapp1-c8e90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1q0WIKYOpH6CZV9-IyED4DWFs_yoJMmk',
    appId: '1:220189526733:android:29c0ca65f795d39d74b784',
    messagingSenderId: '220189526733',
    projectId: 'flutterapp1-c8e90',
    storageBucket: 'flutterapp1-c8e90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtm36XxluG0sMw8etKzzinaa8sAcss0so',
    appId: '1:220189526733:ios:31c73578e21bc1bf74b784',
    messagingSenderId: '220189526733',
    projectId: 'flutterapp1-c8e90',
    storageBucket: 'flutterapp1-c8e90.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtm36XxluG0sMw8etKzzinaa8sAcss0so',
    appId: '1:220189526733:ios:31c73578e21bc1bf74b784',
    messagingSenderId: '220189526733',
    projectId: 'flutterapp1-c8e90',
    storageBucket: 'flutterapp1-c8e90.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfnxYL5Es6q_Jldkp6JvNajCgzUu6Dwf0',
    appId: '1:220189526733:web:d0be395e494440c074b784',
    messagingSenderId: '220189526733',
    projectId: 'flutterapp1-c8e90',
    authDomain: 'flutterapp1-c8e90.firebaseapp.com',
    storageBucket: 'flutterapp1-c8e90.firebasestorage.app',
  );

}